# sudo required cuz we gotta upgrade cmake
sudo: required
#dist: trusty

language: cpp
compiler:
  - gcc
  - clang
notifications:
  email: false
  slack: factmusic:10PHwS7fLCYhMydiIS2cPigw
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
# lifted from https://github.com/elemental/Elemental/blob/master/.travis.yml
- curl https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    
cache:
  bundler: true
  # not sure if we need to explicitly cache usr, specifically want to cache our cmake
  directories:
      - /usr

before_install:
- echo $LANG

# https://gist.github.com/petrbel/c3bf7e0f59c22a52f534 interesting submodule magic

before_script:
- cd test
- mkdir build
- cd build
- cmake ..

script:
- make -j2
- ./util.embedded.tests
