sudo: false
language: cpp
compiler:
  - gcc
  - clang
notifications:
  email: false
  slack: factmusic:10PHwS7fLCYhMydiIS2cPigw
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

before_install:
- echo $LANG

# https://gist.github.com/petrbel/c3bf7e0f59c22a52f534 interesting submodule magic

script:
- cd test
- make
- ./test
