#pragma once

#ifndef MEMORY_OPT
#define CONSOLE_FEATURE_FULL
#endif

#ifdef CONSOLE_FEATURE_FULL
#define CONSOLE_FEATURE_AUTOCOMPLETE
#define CONSOLE_FEATURE_ENHANCED_CHARPROCESSOR 
#endif
//#define CONSOLE_FEATURE_MULTICONSOLE
//#define CONSOLE_BEHAVIOR_PROPAGATE
