#pragma once

// If not specified, optimize for both code and data
#ifdef MEMORY_OPT
#define MEMORY_OPT_CODE   // Optimize down code SIZE
#define MEMORY_OPT_DATA   // Optimize down data SIZE
#endif

#if !defined(MEMORY_OPT_CODE)
#define CONSOLE_FEATURE_FULL
#if !defined(MEMORY_OPT_DATA) || MEMORY_OPT_DATA < 1
#define SERVICE_FEATURE_FULL
#else
#endif
#endif

#if defined(CONSOLE_FEATURE_FULL) && !defined(CONSOLE_FEATURE_FULL_SUPPRESS)
#define CONSOLE_FEATURE_AUTOCOMPLETE
#define CONSOLE_FEATURE_ENHANCED_CHARPROCESSOR
#endif

#if defined(SERVICE_FEATURE_FULL) && !defined(SERVICE_FEATURE_FULL_SUPPRESS)
#define SERVICE_FEATURE_EVENTS
#define SERVICE_FEATURE_RETAINED_STARTFUNC
#define SERVICE_FEATURE_RETAINED_DEPENDENCY
#endif
//#define CONSOLE_FEATURE_MULTICONSOLE
//#define CONSOLE_BEHAVIOR_PROPAGATE

#define DRIVER_FEATURE_VTABLE
